### ISSUE TITLE
[Improvement] Remove reflection stuff

### ISSUE THREAD

**Issue by felipebaltazar** [felipebaltazar/FeatureFlag.Management#5]
## Description
We should remove reflection from `BaseFeature` using source generators to build the default values.
This change will set `FeatureFlag.Management.Firebase` as required dependency.. so we need to change this package name to `FeatureFlag.Management.Analyzer`

## Tasks

- [ ] Remove `BaseFeature` processing for default value
- [ ] Update `BaseFeature` to be `partial class`
- [ ] Update generator to build default values as constants
- [ ] Fix workflows
