### ISSUE TITLE
[Doc] Improve docs

### ISSUE THREAD

**Issue by felipebaltazar** [felipebaltazar/FeatureFlag.Management#7]
## Description
We should write more examples about how to use `FeatureFlag.Management` package.
A "Contribute" session will be necessary too.

## Tasks

- [ ] Example to use this package with Firebase Remote Config
- [ ] Example to use this package with Azure Configuration
- [ ] Example to use this package with a WebSocket service as config
- [ ] Contribute session describing requirements
